import { describe,expect,it } from 'vitest';
import { seedState } from '../data/seed';
import { calculateTeachingGroupCapacity } from './courseCapacityService';
import { activeClassGroups,changeCurrentPosition,classOverview,courseMapItemState,currentCourseItem,currentSectionProgress,groupedCourseMap,lessonHistoryForGroup,nextLessonForGroup,overviewTeachingGroups,weeklyScheduleForGroup } from './classViewService';

const fresh=()=>JSON.parse(JSON.stringify(seedState));
const group=(state,id)=>state.teachingGroups.find(item=>item.id===id);

describe('Stage 4A class views',()=>{
 it('exposes exactly 13 active real classes with textbooks, colors and schedules',()=>{const state=fresh();expect(activeClassGroups(state,'2026-08-16')).toHaveLength(13);const item=group(state,'grade3-a');expect(item).toMatchObject({displayName:'3А',textbook:'Spotlight 3',color:'green'});expect(weeklyScheduleForGroup(state,item,'2026-08-16').map(({day,lessonNumber,startTime,endTime})=>({day,lessonNumber,startTime,endTime}))).toEqual([{day:'Monday',lessonNumber:5,startTime:'12:00',endTime:'12:40'},{day:'Tuesday',lessonNumber:4,startTime:'11:10',endTime:'11:50'}]);});
 it('includes a dynamically added future-active class in Overview while excluding archived and invalid groups',()=>{const state=fresh();const added={...state.teachingGroups.find(item=>item.id==='grade8-a'),id:'group-stable-8b',displayName:'8Б',section:'Б',activeFrom:'2026-09-10'};state.teachingGroups.push(added,{...added,id:'archived-8v',displayName:'8В',archivedAt:'2026-08-20'},{...added,id:'invalid-map',courseMapId:'missing'});state.teachingGroupCourseStates[added.id]={teachingGroupId:added.id,courseMapId:'grade-8',currentPosition:0,lessonAssignments:{}};state.weeklyTimetableVersions=[{id:'base',effectiveFrom:'2026-01-01',entries:state.weeklyTimetable},{id:'active',effectiveFrom:'2026-09-10',entries:[...state.weeklyTimetable,{id:'group-stable-8b-thursday-7',day:'Thursday',lessonNumber:7,teachingGroupId:added.id}]}];const overview=overviewTeachingGroups(state);expect(overview.filter(item=>item.id===added.id)).toHaveLength(1);expect(overview.some(item=>item.id==='archived-8v'||item.id==='invalid-map')).toBe(false);expect(classOverview(state,added,new Date('2026-08-25T12:00:00')).schedule).toEqual([expect.objectContaining({day:'Thursday',lessonNumber:7})]);});
 it('resolves the next actual lesson and exact Course Map content',()=>{const state=fresh();const item=group(state,'grade3-a');const next=nextLessonForGroup(state,item,new Date('2026-08-16T12:00:00'));expect(next).toMatchObject({date:'2026-08-17',number:5,start:'12:00',end:'12:40',courseMapItemId:'g3-001'});expect(next.contentSnapshot).toMatchObject({code:'Starter Lesson',title:'Welcome back!'});expect(classOverview(state,item,new Date('2026-08-16T12:00:00')).nextLesson.id).toBe(next.id);});
 it('keeps positions and reserve calculations independent for groups sharing a template',()=>{const state=fresh();const template=JSON.stringify(state.courseMaps['grade-3']);const beforeOther=JSON.stringify(state.teachingGroupCourseStates['grade3-b']);const moved=changeCurrentPosition(state,'grade3-a','g3-005');expect(currentCourseItem(moved,group(moved,'grade3-a')).id).toBe('g3-005');expect(currentCourseItem(moved,group(moved,'grade3-b')).id).toBe('g3-001');expect(JSON.stringify(moved.teachingGroupCourseStates['grade3-b'])).toBe(beforeOther);expect(JSON.stringify(moved.courseMaps['grade-3'])).toBe(template);expect(calculateTeachingGroupCapacity(moved,'grade3-a').remainingReserve).toBe(6);expect(calculateTeachingGroupCapacity(moved,'grade3-b').remainingReserve).toBe(6);});
 it('protects history snapshots when current position changes',()=>{const state=fresh();state.lessons.push({id:'history-1',date:'2026-08-10',number:5,start:'12:00',end:'12:40',teachingGroupId:'grade3-a',courseMapItemId:'g3-001',contentSnapshot:{code:'Original code',title:'Original title',type:'lesson'},manualStatus:null});const before=JSON.stringify(state.lessons);const moved=changeCurrentPosition(state,'grade3-a','g3-005');expect(JSON.stringify(moved.lessons)).toBe(before);expect(lessonHistoryForGroup(moved,group(moved,'grade3-a'),new Date('2026-08-16')).at(0).contentSnapshot.title).toBe('Original title');});
 it('groups exact Course Map items and distinguishes reserve/current/upcoming states',()=>{const state=fresh();const item=group(state,'grade3-a');const sections=groupedCourseMap(state,item);expect(sections.flatMap(section=>section.items).find(value=>value.id==='g3-001')).toMatchObject({code:'Starter Lesson',title:'Welcome back!'});const reserve=sections.flatMap(section=>section.items).find(value=>value.type==='reserve');expect(courseMapItemState(state,item,state.courseMaps['grade-3'].items[0])).toBe('current');expect(courseMapItemState(state,item,reserve)).toBe('reserve');expect(currentSectionProgress(state,item,new Date('2025-12-01'))).toMatchObject({completed:0});});
 it('handles the pre-year state without fake history and finds the first real event',()=>{const state=fresh();const item=group(state,'grade3-a');expect(lessonHistoryForGroup(state,item,new Date('2025-12-01'))).toEqual([]);expect(nextLessonForGroup(state,item,new Date('2025-12-01T12:00:00'))).toMatchObject({date:'2026-01-05',number:5});});
});
