import { describe,expect,it } from 'vitest';
import { seedState } from '../data/seed';
import { lessonRowStatusTypes } from '../utils/lessons';
import { applyCarryForward,availablePlannedLessons,cancelLesson,changePlannedLesson,createCustomLessonForEvent,findLesson,rescheduleConflict,rescheduleLesson,restoreLesson,saveLessonFields } from './lessonDetailsService';
import { calculateTeachingGroupCapacity } from './courseCapacityService';

const fresh=()=>{const state=JSON.parse(JSON.stringify(seedState));state.lessons=[
 {id:'lesson-1',date:'2026-08-12',number:4,start:'11:10',end:'11:50',teachingGroupId:'grade2-a',courseMapItemId:'g2-001',code:'Reading Lesson 1',contentSnapshot:{code:'Reading Lesson 1',title:'Letters E, T, N, P',type:'lesson'},manualStatus:null,needsAttention:false,carriedIn:'',homework:'',unfinished:'',carryForward:false},
 {id:'lesson-2',date:'2026-08-17',number:5,start:'12:00',end:'12:40',teachingGroupId:'grade3-a',courseMapItemId:'g3-002',code:'Starter Lesson b',contentSnapshot:{code:'Starter Lesson b',title:'Welcome back!',type:'lesson'},manualStatus:null,needsAttention:false,carriedIn:'',homework:'',unfinished:'',carryForward:false},
 ];return state;};

describe('Lesson Details domain integration',()=>{
 it('autosaves all editable content and resets Carry when unfinished is cleared',()=>{let state=fresh();state=saveLessonFields(state,'lesson-2',{whatWeDid:'Past simple',didntFinish:'Exercise 4',carryToNextLesson:true,teacherNotes:'Repeat verbs',homework:'Page 12',homeworkMaterials:[{id:'m1',type:'URL',title:'Practice',url:'https://example.com'}]});expect(findLesson(state,'lesson-2')).toMatchObject({whatWeDid:'Past simple',unfinished:'Exercise 4',carryForward:true,teacherNotes:'Repeat verbs',homework:'Page 12'});state=saveLessonFields(state,'lesson-2',{didntFinish:'',carryToNextLesson:true});expect(findLesson(state,'lesson-2').carryForward).toBe(false);});
 it('carries text only to the next real lesson and removes it when Carry is cleared',()=>{let state=saveLessonFields(fresh(),'lesson-1',{didntFinish:'Workbook page 5',carryToNextLesson:true});state=applyCarryForward(state,'lesson-1');const target=state.lessons.find(item=>item.carriedFromLessonId==='lesson-1');expect(target).toMatchObject({needsAttention:true,carriedIn:'Workbook page 5',teachingGroupId:'grade2-a'});state=saveLessonFields(state,'lesson-1',{didntFinish:'',carryToNextLesson:false});state=applyCarryForward(state,'lesson-1');expect(state.lessons.some(item=>item.carriedFromLessonId==='lesson-1'&&item.needsAttention)).toBe(false);});
 it('keeps received carry read-only and separate from the receiving lesson unfinished field',()=>{let state=fresh();const source=findLesson(state,'lesson-2');state=saveLessonFields(state,source.id,{didntFinish:'Speaking activity',carryToNextLesson:true});state=applyCarryForward(state,source.id);const receiver=state.lessons.find(item=>item.carriedFromLessonId===source.id);expect(receiver).toMatchObject({carriedIn:'Speaking activity',unfinished:'',carryForward:false,needsAttention:true});expect(findLesson(state,source.id).needsAttention).toBe(false);});
 it('does not propagate received text unless the receiving lesson explicitly carries its own unfinished work',()=>{let state=saveLessonFields(fresh(),'lesson-2',{didntFinish:'Speaking activity',carryToNextLesson:true});state=applyCarryForward(state,'lesson-2');const receiver=state.lessons.find(item=>item.carriedFromLessonId==='lesson-2');expect(state.lessons.some(item=>item.carriedFromLessonId===receiver.id)).toBe(false);state=saveLessonFields(state,receiver.id,{didntFinish:'Speaking activity',carryToNextLesson:true});state=applyCarryForward(state,receiver.id);const next=state.lessons.find(item=>item.carriedFromLessonId===receiver.id);expect(next).toMatchObject({carriedIn:'Speaking activity',needsAttention:true,unfinished:''});});
 it('unchecking Carry removes only its target carry reason and preserves unrelated attention',()=>{let state=saveLessonFields(fresh(),'lesson-2',{didntFinish:'Speaking activity',carryToNextLesson:true});state=applyCarryForward(state,'lesson-2');const receiver=state.lessons.find(item=>item.carriedFromLessonId==='lesson-2');state={...state,lessons:state.lessons.map(item=>item.id===receiver.id?{...item,attentionReasons:[...item.attentionReasons,'manual-review'],needsAttention:true}:item)};state=saveLessonFields(state,'lesson-2',{carryToNextLesson:false});state=applyCarryForward(state,'lesson-2');expect(findLesson(state,receiver.id)).toMatchObject({carriedIn:'',carriedFromLessonId:null,needsAttention:true,attentionReasons:['manual-review']});});
 it('changes one group assignment without consuming reserve or changing another group',()=>{const before=fresh();const capacity=calculateTeachingGroupCapacity(before,'grade3-a').remainingReserve;const other=JSON.stringify(before.teachingGroupCourseStates['grade2-a']);const item=before.courseMaps['grade-3'].items.filter(x=>x.type==='lesson').find(x=>x.id!=='g3-002');const state=changePlannedLesson(before,'lesson-2',item);expect(findLesson(state,'lesson-2').courseMapItemId).toBe(item.id);expect(calculateTeachingGroupCapacity(state,'grade3-a').remainingReserve).toBe(capacity);expect(JSON.stringify(state.teachingGroupCourseStates['grade2-a'])).toBe(other);expect(state.teachingGroupCourseStates['grade3-a'].returnedPlannedLessons.at(-1).courseMapItemId).toBe('g3-002');});
 it('custom lessons consume reserve and return the planned topic',()=>{const before=fresh();const reserve=calculateTeachingGroupCapacity(before,'grade3-a').remainingReserve;const state=createCustomLessonForEvent(before,'lesson-2',{title:'Revision games'});expect(findLesson(state,'lesson-2').contentSnapshot).toMatchObject({type:'custom',title:'Revision games'});expect(calculateTeachingGroupCapacity(state,'grade3-a').remainingReserve).toBe(reserve-1);expect(state.teachingGroupCourseStates['grade3-a'].returnedPlannedLessons.at(-1).courseMapItemId).toBe('g3-002');});
 it('cancel and restore preserve content and return reserve',()=>{const before=fresh();const reserve=calculateTeachingGroupCapacity(before,'grade3-a').remainingReserve;let state=cancelLesson(before,'lesson-2');expect(findLesson(state,'lesson-2').manualStatus).toBe('cancelled');expect(calculateTeachingGroupCapacity(state,'grade3-a').remainingReserve).toBe(reserve-1);state=restoreLesson(state,'lesson-2');expect(findLesson(state,'lesson-2').manualStatus).toBe(null);expect(calculateTeachingGroupCapacity(state,'grade3-a').remainingReserve).toBe(reserve);expect(findLesson(state,'lesson-2').contentSnapshot.code).toBe('Starter Lesson b');});
 it('reschedules without consuming reserve, preserves the source, and marks the moved event',()=>{const before=fresh();const reserve=calculateTeachingGroupCapacity(before,'grade3-a').remainingReserve;const state=rescheduleLesson(before,'lesson-2',{date:'2026-08-19',number:7});const source=findLesson(state,'lesson-2');const moved=state.lessons.find(item=>item.rescheduledSourceId==='lesson-2');expect(source.manualStatus).toBe('rescheduled');expect(moved).toMatchObject({date:'2026-08-19',number:7,teachingGroupId:'grade3-a',rescheduled:true});expect(lessonRowStatusTypes(moved,new Date('2026-08-19T08:00:00'))[0]).toBe('rescheduled');expect(calculateTeachingGroupCapacity(state,'grade3-a').remainingReserve).toBe(reserve);});
 it('blocks occupied reschedule slots',()=>{const conflict=rescheduleConflict(fresh(),{date:'2026-08-17',number:3,teachingGroupId:'grade3-a',ignoreLessonId:'lesson-2'});expect(conflict.label).toMatch(/^Occupied by /);expect(()=>rescheduleLesson(fresh(),'lesson-2',{date:'2026-08-17',number:3})).toThrow(/Occupied by/);});
 it('keeps historical snapshots when a Course Map changes',()=>{const state=fresh();const original=findLesson(state,'lesson-2').contentSnapshot;state.courseMaps['grade-3'].items.find(item=>item.id==='g3-002').code='Replacement';expect(findLesson(state,'lesson-2').contentSnapshot).toEqual(original);});
 it('supports cancel, restore, notes and reschedule for an individual without a Course Map',()=>{const state=fresh();state.teachingGroups.push({id:'student-1',type:'individual',displayName:'Alex',courseMapId:null,color:'mint',activeFrom:'2026-01-01'});state.lessons.push({id:'individual-lesson',date:'2026-08-16',number:7,start:'14:00',end:'14:40',teachingGroupId:'student-1',code:'Conversation',contentSnapshot:{code:'Conversation',title:null,type:'custom'},manualStatus:null});let next=saveLessonFields(state,'individual-lesson',{teacherNotes:'Good progress'});next=cancelLesson(next,'individual-lesson');next=restoreLesson(next,'individual-lesson');next=rescheduleLesson(next,'individual-lesson',{date:'2026-08-19',number:7});expect(findLesson(next,'individual-lesson').teacherNotes).toBe('Good progress');expect(next.lessons.find(item=>item.rescheduledSourceId==='individual-lesson')).toBeTruthy();});
 it('returns exact Course Map code/title values and excludes the current item',()=>{const state=fresh();const current=findLesson(state,'lesson-2');const items=availablePlannedLessons(state,current);expect(items.some(item=>item.id===current.courseMapItemId)).toBe(false);expect(items.find(item=>item.id==='g3-001')).toMatchObject({code:'Starter Lesson a',title:'Welcome back!'});expect(items.find(item=>item.code==='Module 1 Test')?.title).toBeNull();expect(items.find(item=>item.id==='g3-005')).toMatchObject({code:'Module 1 Lesson 2a',title:'School subjects'});});
});
