import { describe,expect,it } from 'vitest';
import { seedState } from '../data/seed';
import { lessonsForDate } from './lessonViewService';
import { applyAcademicCalendar,applyWeeklyTimetable,exportBackup,importBackup,previewBackup } from './settingsService';
import { calculateTeachingGroupCapacity } from './courseCapacityService';
import { addBellScheduleVersion,resolveLessonEventTime,resolveTimetableLesson } from './bellSchedule';
import { archiveTeachingGroup,findScheduleConflicts,saveTeachingGroup,teachingGroupFilterOptions } from './teachingGroupService';
import { migrateState } from '../utils/storage';

const fresh=()=>JSON.parse(JSON.stringify(seedState));

describe('Stage 4B Settings',()=>{
 it('allows fixed school-break rows to remain empty while saving the academic year',()=>{const state=applyAcademicCalendar(fresh(),{academicYear:{start:'2026-09-07',end:'2027-05-31'},schoolBreaks:[{label:'Autumn Break',start:'',end:''},{label:'Winter Break',start:'',end:''},{label:'Spring Break',start:'',end:''}],noSchoolDays:[],excludedDates:[]});expect(state.academicCalendar.academicYear.start).toBe('2026-09-07');});
 it('excludes school breaks and individual holidays without creating cancelled events',()=>{const state=applyAcademicCalendar(fresh(),{academicYear:{start:'2026-01-01',end:'2026-12-31'},schoolBreaks:[{id:'autumn',start:'2026-08-17',end:'2026-08-21',label:'Autumn'}],noSchoolDays:[{id:'holiday',date:'2026-08-24',label:'Holiday'}],excludedDates:[]});expect(lessonsForDate(state,new Date(2026,7,17))).toEqual([]);expect(lessonsForDate(state,new Date(2026,7,24))).toEqual([]);expect(state.lessons).toEqual([]);});
 it('calculates annual slots and effective reserve independently by group timetable',()=>{let state=fresh();state=applyAcademicCalendar(state,{academicYear:{start:'2026-09-01',end:'2027-05-31'},schoolBreaks:[{start:'2026-12-28',end:'2027-01-10',label:'Winter'}],noSchoolDays:[{date:'2026-11-04',label:'Holiday'}],excludedDates:[]});const twoA=calculateTeachingGroupCapacity(state,'grade2-a');const threeA=calculateTeachingGroupCapacity(state,'grade3-a');expect(twoA.availableScheduledSlots).toBeGreaterThan(0);expect(threeA.availableScheduledSlots).toBeGreaterThan(0);expect(twoA.teachingGroupId).not.toBe(threeA.teachingGroupId);expect(twoA.maximumEffectiveReserve).toBe(Math.min(twoA.templateReserve,Math.max(0,twoA.availableScheduledSlots-twoA.requiredPlannedLessons)));});
 it('versions bell times while historical event snapshots remain unchanged',()=>{const original={date:'2026-09-01',number:1,start:'08:30',end:'09:10'};const state=addBellScheduleVersion(fresh(),{effectiveFrom:'2026-10-01',slots:seedState.bellSchedules[0].slots.map(x=>x.lessonNumber===1?{...x,startTime:'09:00',endTime:'09:40'}:x)});expect(resolveLessonEventTime(state,original)).toMatchObject({start:'08:30',end:'09:10',source:'historical-snapshot'});expect(resolveTimetableLesson(state,'2026-10-06','Tuesday',1)?.start).toBe('09:00');});
 it('blocks occupied slots and supports an individual without Course Map or reserve state',()=>{const state=fresh();const individual={id:'student-test',type:'individual',grade:8,section:null,displayName:'Student',textbook:'',courseMapId:null,color:'lavender',activeFrom:'2026-01-01',archivedAt:null};expect(findScheduleConflicts(state,individual,[{day:'Tuesday',lessonNumber:5}])[0].displayName).toBe('3Б');const saved=saveTeachingGroup(state,individual,[{day:'Thursday',lessonNumber:7}]);expect(saved.saved).toBe(true);expect(saved.state.teachingGroupCourseStates['student-test']).toBeUndefined();expect(teachingGroupFilterOptions(saved.state.teachingGroups,'2026-08-16').at(-1).label).toBe('Individual');});
 it('archives only future generation and preserves historical records',()=>{const state=fresh();state.lessons=[{id:'history',date:'2026-08-10',teachingGroupId:'grade3-a',number:5,start:'12:00',end:'12:40',contentSnapshot:{code:'Stored',title:'Snapshot'}}];const archived=archiveTeachingGroup(state,'grade3-a','2026-08-16');expect(archived.lessons[0].contentSnapshot.title).toBe('Snapshot');expect(lessonsForDate(archived,new Date(2026,7,17)).some(x=>x.teachingGroupId==='grade3-a')).toBe(false);});
 it('exports and restores a complete versioned backup atomically',()=>{const state=fresh();const json=exportBackup(state);const preview=previewBackup(json);expect(preview.valid).toBe(true);expect(preview.summary).toMatchObject({groups:13,maps:5});expect(importBackup(json)).toEqual(state);expect(previewBackup('{bad').valid).toBe(false);});
 it('migrates schema 8 without clearing real groups or lesson history',()=>{const old=fresh();old.schemaVersion=8;old.lessons=[{id:'historic'}];delete old.academicCalendar.schoolBreaks;delete old.academicCalendar.noSchoolDays;const migrated=migrateState(old);expect(migrated.schemaVersion).toBe(10);expect(migrated.teachingGroups).toHaveLength(13);expect(migrated.lessons).toEqual([{id:'historic'}]);expect(migrated.academicCalendar.schoolBreaks).toEqual([]);});
 it('removes only empty generated phantom events outside the academic year',()=>{const old=fresh();old.schemaVersion=9;old.academicCalendar.academicYear={start:'2026-09-07',end:'2027-05-31'};old.lessons=[{id:'planned-2026-08-12-slot',date:'2026-08-12',number:1,start:'08:30',end:'09:10',teachingGroupId:'grade4-a',courseMapItemId:'g4-001',contentSnapshot:{code:'Starter Lesson a',title:'Back together!',type:'lesson'}},{id:'planned-2026-08-14-saved',date:'2026-08-14',number:1,start:'08:30',end:'09:10',teachingGroupId:'grade4-a',teacherNotes:'Keep this record',contentSnapshot:{code:'Saved',type:'lesson'}}];const migrated=migrateState(old);expect(migrated.lessons.map(item=>item.id)).toEqual(['planned-2026-08-14-saved']);});
 it('applies weekly timetable changes only from their effective date without rewriting stored lessons',()=>{const state=fresh();state.lessons=[{id:'historic',date:'2026-08-01',start:'08:30',end:'09:10'}];const entries=state.weeklyTimetable.filter(x=>x.teachingGroupId!=='grade2-a');const changed=applyWeeklyTimetable(state,entries,'2026-08-16');const asOf=new Date(2026,7,1);expect(changed.lessons).toEqual(state.lessons);expect(changed.weeklyTimetable.some(x=>x.teachingGroupId==='grade2-a')).toBe(false);expect(lessonsForDate(changed,new Date(2026,7,12),asOf).some(x=>x.teachingGroupId==='grade2-a')).toBe(true);expect(lessonsForDate(changed,new Date(2026,7,19),asOf).some(x=>x.teachingGroupId==='grade2-a')).toBe(false);});
});
