import { describe,expect,it } from 'vitest';
import { seedState } from '../data/seed';
import { PASTEL_PALETTE } from '../data/pastelPalette';
import { archiveTeachingGroup,findScheduleConflicts,saveTeachingGroup,teachingGroupFilterOptions } from './teachingGroupService';
import { lessonsForDate } from './lessonViewService';
import { calculateTeachingGroupCapacity } from './courseCapacityService';

const copy=value=>JSON.parse(JSON.stringify(value));
const individual={id:'individual-masha',type:'individual',displayName:'Masha',grade:8,textbook:'Rainbow English 8',courseMapId:null,color:'lavender',activeFrom:'2026-10-01'};

describe('universal teaching groups',()=>{
 it('loads exactly the 13 real classes with independent states and a conflict-free 27-slot timetable',()=>{expect(seedState.teachingGroups.map(group=>group.displayName)).toEqual(['2А','2Б','2В','3А','3Б','3В','4А','4Б','4В','5А','5Б','5В','8А']);expect(seedState.weeklyTimetable).toHaveLength(27);expect(new Set(seedState.weeklyTimetable.map(entry=>`${entry.day}:${entry.lessonNumber}`)).size).toBe(27);expect(Object.keys(seedState.teachingGroupCourseStates)).toHaveLength(13);expect(new Set(Object.values(seedState.teachingGroupCourseStates)).size).toBe(13);for(const group of seedState.teachingGroups){const slots=seedState.weeklyTimetable.filter(entry=>entry.teachingGroupId===group.id);expect(findScheduleConflicts(seedState,group,slots)).toEqual([]);expect(calculateTeachingGroupCapacity(seedState,group.id).teachingGroupId).toBe(group.id);}expect(teachingGroupFilterOptions(seedState.teachingGroups,'2026-08-16').map(item=>item.label)).toEqual(['All classes','Grade 2','Grade 3','Grade 4','Grade 5','Grade 8']);});
 it('loads all five maps including provisional Grade 2',()=>{expect(Object.keys(seedState.courseMaps).sort()).toEqual(['grade-2','grade-3','grade-4','grade-5','grade-8']);expect(seedState.courseMaps['grade-2']).toMatchObject({provisional:true,plannedItemCount:60,reserveCount:6,reserveScope:'annual'});});
 it('keeps approved defaults and supports curated custom colors',()=>{expect([...new Set(seedState.teachingGroups.map(x=>x.color))]).toEqual(['pink','green','coral','yellow','blue']);expect(PASTEL_PALETTE).toHaveLength(12);const result=saveTeachingGroup(copy(seedState),{id:'grade3-g',type:'class',grade:3,section:'Г',displayName:'3Г',textbook:'Spotlight 3',courseMapId:'grade-3',color:'mint',activeFrom:'2026-09-01'},[{day:'Wednesday',lessonNumber:7}]);expect(result.saved).toBe(true);expect(result.state.teachingGroups.find(x=>x.id==='grade3-g').color).toBe('mint');});
 it('allows an individual without grade or Course Map',()=>{const result=saveTeachingGroup(copy(seedState),{...individual,grade:null},[{day:'Wednesday',lessonNumber:7}]);expect(result.saved).toBe(true);expect(result.state.teachingGroups.at(-1).courseMapId).toBeNull();});
 it('detects and blocks an overlapping weekly conflict',()=>{const conflicts=findScheduleConflicts(seedState,individual,[{day:'Monday',lessonNumber:3}]);expect(conflicts[0]).toMatchObject({displayName:'5А',startTime:'10:15',endTime:'10:55'});expect(saveTeachingGroup(seedState,individual,[{day:'Monday',lessonNumber:3}]).saved).toBe(false);});
 it('respects activeFrom, archive, and Individual filters',()=>{let result=saveTeachingGroup(copy(seedState),individual,[{day:'Wednesday',lessonNumber:7}]).state;expect(lessonsForDate(result,new Date(2026,8,30,12)).some(x=>x.teachingGroupId===individual.id)).toBe(false);expect(teachingGroupFilterOptions(result.teachingGroups,'2026-10-01').at(-1).value).toBe('individual');result=archiveTeachingGroup(result,individual.id,'2026-11-01');expect(lessonsForDate(result,new Date(2026,10,4,12)).some(x=>x.teachingGroupId===individual.id)).toBe(false);expect(result.lessons).toHaveLength(seedState.lessons.length);});
});
