import { useEffect,useMemo,useRef,useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import { LessonDetailIcon,StatusIcon } from '../components/Icons';
import { teachingGroupColorStyle } from '../data/pastelPalette';
import { addDays,dayMonth,dayMonthYear,isoDate,parseIsoDate,weekday } from '../utils/date';
import { lessonStatus } from '../utils/lessons';
import { applyCarryForward,availablePlannedLessons,cancelLesson,changePlannedLesson,createCustomLessonForEvent,findLesson,rescheduleConflict,rescheduleLesson,rescheduleOptions,reserveForLesson,restoreLesson,sameDayLessonNavigation,saveLessonFields } from '../services/lessonDetailsService';

const Arrow=({direction})=><span aria-hidden="true">{direction==='left'?'←':'→'}</span>;
const Modal=({title,children,onClose})=><div className="lesson-modal-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="lesson-modal" role="dialog" aria-modal="true" aria-labelledby="lesson-modal-title"><button className="modal-close" onClick={onClose} aria-label="Close">×</button><h2 id="lesson-modal-title">{title}</h2>{children}</section></div>;

export default function LessonDetails({state,update}){
 const {id}=useParams();const navigate=useNavigate();const lesson=findLesson(state,id);const [draft,setDraft]=useState(null);const [saveStatus,setSaveStatus]=useState('saved');const [panel,setPanel]=useState(null);const first=useRef(true);
 useEffect(()=>{if(!lesson)return;first.current=true;setDraft({whatWeDid:lesson.whatWeDid||'',didntFinish:lesson.unfinished||'',carryToNextLesson:Boolean(lesson.unfinished&&lesson.carryForward),teacherNotes:lesson.teacherNotes||'',homework:lesson.homework||'',homeworkMaterials:lesson.homeworkMaterials||[]});setSaveStatus('saved');},[id]);
 useEffect(()=>{const enabled=Boolean(lesson?.carriedIn);document.documentElement.classList.toggle('lesson-details-scroll',enabled);document.body.classList.toggle('lesson-details-scroll',enabled);return()=>{document.documentElement.classList.remove('lesson-details-scroll');document.body.classList.remove('lesson-details-scroll');};},[lesson?.carriedIn]);
 useEffect(()=>{if(!draft||!lesson||first.current){first.current=false;return;}setSaveStatus('saving');const timer=setTimeout(()=>{update(current=>applyCarryForward(saveLessonFields(current,id,draft),id));setSaveStatus('saved');},450);return()=>clearTimeout(timer);},[draft,id]);
 const setField=(key,value)=>setDraft(current=>{const next={...current,[key]:value};if(key==='didntFinish'&&!value.trim())next.carryToNextLesson=false;return next;});
 const group=state.teachingGroups.find(item=>item.id===lesson?.teachingGroupId);const snapshot=lesson?.contentSnapshot||{};const navigation=lesson?sameDayLessonNavigation(state,lesson):{};const primary=lesson?lessonStatus(lesson):null;const capacity=lesson?reserveForLesson(state,lesson):null;
 if(!lesson)return <section className="placeholder card"><span>Lesson details</span><h1>Lesson not found</h1><button onClick={()=>navigate('/day')}>Back to Day</button></section>;
 const goToLesson=target=>target&&navigate(`/lesson/${target.id}`);
 const doCancel=()=>{const zero=capacity?.remainingReserve===0;const remaining=Math.max(0,(capacity?.remainingReserve||0)-1);if(window.confirm(zero?'No reserve capacity left. Cancelling may push planned content beyond the academic year. Continue?':`Cancel this lesson?\n1 reserve lesson will be used.\n${remaining} reserve lessons will remain.`))update(current=>cancelLesson(current,id,{confirmed:zero}));};
 const doRestore=()=>{if(window.confirm('Restore this lesson and recalculate future assignments?'))update(current=>restoreLesson(current,id));};
 return <div className={`lesson-details-page internal-page ${lesson.carriedIn?'has-carried':''}`}>
  <section className="lesson-nav-pill">
   <button className="back-day" onClick={()=>navigate(`/day?date=${lesson.date}`)}>← Back to day</button>
   <button className="lesson-neighbour previous" disabled={!navigation.previous} onClick={()=>goToLesson(navigation.previous)}><i><Arrow direction="left"/></i><span>Previous lesson</span></button>
   <div className="lesson-nav-title"><strong>{weekday(parseIsoDate(lesson.date))}</strong><b>/</b><span>{dayMonth(parseIsoDate(lesson.date))}</span><b>/</b><span>Lesson {lesson.number}</span></div>
   <button className="lesson-neighbour next" disabled={!navigation.next} onClick={()=>goToLesson(navigation.next)}><span>Next lesson</span><i><Arrow direction="right"/></i></button>
  </section>
  <section className="lesson-info-grid">
   <article className="lesson-info-card"><LessonDetailIcon type="time"/><div><small>Time</small><strong>{lesson.start}–{lesson.end}</strong></div></article>
   <article className="lesson-info-card group-info" style={teachingGroupColorStyle(group)}><LessonDetailIcon type="group"/><div><small>Teaching group</small><strong>{group?.displayName||lesson.teachingGroupId}</strong></div></article>
   <article className="lesson-info-card content-info"><LessonDetailIcon type="content"/><div><small>Lesson content</small><strong className="lesson-structure-label">{snapshot.code||lesson.code}</strong>{snapshot.title&&<span className="lesson-title-label">{snapshot.title}</span>}</div>{group?.courseMapId&&primary!=='cancelled'&&<button className="change-lesson-button" onClick={()=>setPanel('change')}><span>Change lesson</span><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M3 5.5 8 10.5l5-5"/></svg></button>}</article>
   <article className="lesson-info-card status-info"><LessonDetailIcon type="status"/><div><small>Status</small><div><StatusIcon type={primary} size="small"/><strong>{primary[0].toUpperCase()+primary.slice(1)}</strong>{lesson.needsAttention&&<span className="attention-flag"><StatusIcon type="attention" size="small"/><em>Needs attention</em></span>}</div></div></article>
  </section>
  <section className="lesson-work-grid card">
   <article className="lesson-work-card">
    {lesson.carriedIn&&<aside className="carried-work"><strong>From previous lesson</strong><p>{lesson.carriedIn}</p></aside>}
    <label><span className="work-label did-label"><LessonDetailIcon type="did"/>What we did</span><textarea value={draft?.whatWeDid||''} onChange={event=>setField('whatWeDid',event.target.value)} placeholder="What was completed during the lesson?"/></label>
    <label><span className="work-label unfinished-label"><LessonDetailIcon type="unfinished"/>Didn't finish</span><textarea value={draft?.didntFinish||''} onChange={event=>setField('didntFinish',event.target.value)} placeholder="What still needs attention?"/></label>
    <label className={`carry-check ${!draft?.didntFinish.trim()?'disabled':''}`}><input type="checkbox" disabled={!draft?.didntFinish.trim()} checked={Boolean(draft?.carryToNextLesson)} onChange={event=>setField('carryToNextLesson',event.target.checked)}/><span>Carry unfinished work to next lesson</span></label>
    <label><span className="work-label notes-label"><LessonDetailIcon type="notes"/>Teacher notes</span><textarea value={draft?.teacherNotes||''} onChange={event=>setField('teacherNotes',event.target.value)} placeholder="Private teacher notes"/></label>
   </article>
   <article className="lesson-work-card lesson-homework-card">
    <label><span className="work-label homework-label"><LessonDetailIcon type="homework"/>Homework</span><textarea value={draft?.homework||''} onChange={event=>setField('homework',event.target.value)} placeholder="Homework for this lesson"/></label>
    <div className="materials-head"><h2><LessonDetailIcon type="link"/>Homework links</h2><button onClick={()=>setField('homeworkMaterials',[...draft.homeworkMaterials,{id:`material-${Date.now()}`,type:'URL',title:'',url:''}])}>+ Add link</button></div>
    <div className="homework-materials">{draft?.homeworkMaterials.map((material,index)=><div className="material-row" key={material.id}><input aria-label="Link label" value={material.type||''} placeholder="Type" onChange={event=>setField('homeworkMaterials',draft.homeworkMaterials.map((item,i)=>i===index?{...item,type:event.target.value}:item))}/><input aria-label="Link title" value={material.title||''} placeholder="Title" onChange={event=>setField('homeworkMaterials',draft.homeworkMaterials.map((item,i)=>i===index?{...item,title:event.target.value}:item))}/><input aria-label="Link URL" type="url" value={material.url||''} placeholder="https://" onChange={event=>setField('homeworkMaterials',draft.homeworkMaterials.map((item,i)=>i===index?{...item,url:event.target.value}:item))}/><button aria-label="Remove link" onClick={()=>setField('homeworkMaterials',draft.homeworkMaterials.filter((_,i)=>i!==index))}>×</button></div>)}</div>
    <footer className="lesson-work-footer"><p className={`autosave ${saveStatus}`}>{saveStatus==='saving'?'Saving…':'✓ Saved'}</p><div className="lesson-actions">{primary==='cancelled'?<button className="restore-action" onClick={doRestore}>Restore lesson</button>:<button className="cancel-action" onClick={doCancel}><LessonDetailIcon type="cancel"/>Cancel</button>}<button className="reschedule-action" onClick={()=>setPanel('reschedule')}><LessonDetailIcon type="reschedule"/>Reschedule</button></div></footer>
   </article>
  </section>
  {panel==='change'&&<ChangeLessonModal state={state} lesson={lesson} capacity={capacity} onClose={()=>setPanel(null)} onApply={operation=>{update(operation);setPanel(null)}}/>}
  {panel==='reschedule'&&<RescheduleModal state={state} lesson={lesson} onClose={()=>setPanel(null)} onApply={selection=>{update(current=>rescheduleLesson(current,id,selection));setPanel(null)}}/>}
 </div>;
}

function ChangeLessonModal({state,lesson,capacity,onClose,onApply}){const [custom,setCustom]=useState(false);const [title,setTitle]=useState('');const planned=useMemo(()=>availablePlannedLessons(state,lesson),[state,lesson.id]);const group=state.teachingGroups.find(item=>item.id===lesson.teachingGroupId);const assignedItem=state.courseMaps[group?.courseMapId]?.items.find(item=>item.id===lesson.courseMapItemId);const currentContent=lesson.contentSnapshot?.type==='custom'?lesson.contentSnapshot:(assignedItem||lesson.contentSnapshot||lesson);const choose=item=>{if(window.confirm(`Use this lesson today?\n${item.code}${item.title?` — ${item.title}`:''}\nCurrent planned lesson will return to the future queue.`))onApply(current=>changePlannedLesson(current,lesson.id,item));};const makeCustom=()=>{const zero=capacity?.remainingReserve===0;if(!title.trim())return;if(window.confirm(zero?'No reserve capacity left. Adding a Custom Lesson may push planned content beyond the academic year. Continue?':`This will use 1 reserve lesson.\n${Math.max(0,capacity.remainingReserve-1)} reserve lessons will remain.`))onApply(current=>createCustomLessonForEvent(current,lesson.id,{title:title.trim()},{confirmed:zero}));};return <Modal title="Change lesson" onClose={onClose}>{custom?<div className="custom-lesson-form"><label>Custom lesson title<input autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="Revision games"/></label><p>{capacity?.remainingReserve===0?'No reserve capacity left.':'This will use 1 reserve lesson.'}</p><div><button onClick={()=>setCustom(false)}>Cancel</button><button className="primary-modal-action" onClick={makeCustom}>Create custom lesson</button></div></div>:<><h3>Current lesson</h3><div className="current-lesson-option"><strong>{currentContent.code}</strong>{currentContent.title&&<span>{currentContent.title}</span>}</div><h3>Upcoming planned lessons</h3><div className="planned-options">{planned.slice(0,12).map(item=><button key={item.id} onClick={()=>choose(item)}><strong>{item.code}</strong>{item.title&&<span>{item.title}</span>}</button>)}</div><button className="custom-trigger" onClick={()=>setCustom(true)}>+ Custom lesson</button></>}</Modal>}

function RescheduleModal({state,lesson,onClose,onApply}){const initial=isoDate(addDays(parseIsoDate(lesson.date),1));const [date,setDate]=useState(initial);const [number,setNumber]=useState(null);const suggested=Array.from({length:4},(_,i)=>addDays(parseIsoDate(lesson.date),i+1));const slots=rescheduleOptions(state,date);return <Modal title="Reschedule lesson" onClose={onClose}><h3>Choose date</h3><div className="reschedule-dates">{suggested.map(item=>{const key=isoDate(item);return <button className={date===key?'selected':''} key={key} onClick={()=>{setDate(key);setNumber(null)}}><strong>{weekday(item)}</strong><span>{dayMonth(item)}</span></button>})}</div><label className="another-date">Choose another date…<input type="date" min={initial} value={date} onChange={event=>{setDate(event.target.value);setNumber(null)}}/></label><h3>Choose time</h3><div className="reschedule-slots">{slots.map(slot=>{const conflict=rescheduleConflict(state,{date,number:slot.lessonNumber,teachingGroupId:lesson.teachingGroupId,ignoreLessonId:lesson.id});return <button disabled={Boolean(conflict)} className={number===slot.lessonNumber?'selected':''} key={slot.lessonNumber} onClick={()=>setNumber(slot.lessonNumber)}><strong>Lesson {slot.lessonNumber} · {slot.startTime}–{slot.endTime}</strong>{conflict&&<span>{conflict.label}</span>}</button>})}</div><div className="modal-footer"><button onClick={onClose}>Cancel</button><button className="primary-modal-action" disabled={!number} onClick={()=>onApply({date,number})}>Reschedule</button></div></Modal>}
